'use client';
import { ApolloProvider } from '@apollo/client';
import './globals.css';
import '../css/main.css';
import { Inter } from 'next/font/google';
import { client } from '@/utils/apollo';
import { useBearStore } from '@/store/store';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { handleViewListProduct } = useBearStore((state) => state);
  return (
    <html lang="en">
      <body
        className={inter.className}
        onClick={() => handleViewListProduct(false)}
      >
        <ApolloProvider client={client}>{children}</ApolloProvider>
      </body>
    </html>
  );
}
