'use client';
import { ApolloProvider } from '@apollo/client';
import './globals.css';
import '../css/main.css';
import { Inter } from 'next/font/google';
import { client } from '@/utils/apollo';
import { useBearStore } from '@/store/store';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import ProductModal from '@/components/ProductModal';

import PersistSession from '@/components/PersistSession/PersistSession';
import Loader from '@/components/Loader/Loader';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const { getLogin } = useLogin();

  const { handleViewListProduct, handleViewCart, user, registerUser } =
    useBearStore((state) => state);

  const closeAllModal = () => {
    // if (viewListProduct) {
    handleViewListProduct(false);
    // }
    // if (viewCart) {
    handleViewCart(false);
    // }
  };
  return (
    <html lang="es">
      <body
        // className={inter.className}
        className="body"
        onClick={closeAllModal}
      >
        <ApolloProvider client={client}>
          <ToastContainer
            style={{ fontSize: '.7em', fontWeight: 'normal', color: 'red' }}
          />
          <Loader />
          <Header />
          <PersistSession />
          {children}
          <ProductModal />
          <Footer />
        </ApolloProvider>
      </body>
    </html>
  );
}
